/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Best smite LAS
 */
public class Productos extends javax.swing.JPanel {
    private DefaultTableModel modelo;
    /**
     * Creates new form Menu2
     */
    public Productos() {
        initComponents();
        modelo=new DefaultTableModel();
        armarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(64, 44, 72));
        setPreferredSize(new java.awt.Dimension(1000, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 19, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    GESTIÓN DE PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, -1));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "Nombre", "Cantidad", "Categoria" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 170, -1));

        jtProductos.setBackground(new java.awt.Color(204, 204, 255));
        jtProductos.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 90));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTAR  POR");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 60));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 130, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, 40));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categoria");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 130, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 130, 20));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 100, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 130, 40));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, 20));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 100, 20));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 20));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 100, 20));

        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("* INGRESE  PRECIO *");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 120, 20));

        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("* INGRESE  ID *");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 90, 20));

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("* INGRESE NOMBRE *");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 110, 20));

        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("* INGRESE  CANTIDAD *");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, 20));

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("* INGRESE  CATEGORIA *");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 130, 20));
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables
private void armarCabecera(){
    
          ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID Producto");
        columnas.add("Nombre");
        columnas.add("Cantidad");
        columnas.add("Precio");
        columnas.add("Activo");
        columnas.add("Categoria");
        
        
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jtProductos.setModel(modelo);
    }
}
